### ISSUE TITLE
Scripts did not work

### ISSUE THREAD

**Issue by vetash** [coderofsalvation/hubot-script-shellcmd#2]
I have created new scripts in _hubot_dir_ bash/handlers/ and give them permissions +x on user which run hubot, in shell everything works fine, but not in hubot. What i do wrong?

**Comment by vetash** [comment]
Oh, sorry, forgot about configuration. But where i must to paste this string?
HUBOT_SHELLCMD="/foo/bar/myhandler" 
Please write in detail if is possible. I realy stuck in this. 
Thanks.

**Comment by coderofsalvation** [comment]
see https://github.com/coderofsalvation/hubot-script-shellcmd/issues/1

in short, you can run hubot like this on the commandline:

```
$ HUBOT_SHELLCMD="/foo/bar/myhandler" node <hubotfile>
```

or just put this somewhere in your code:

```
process.env.HUBOT_SHELLCMD="/foo/bar/myhandler";
```

or just put this in your .bashrc or shellscript before launching hubot

```
export HUBOT_SHELLCMD="/foo/bar/myhandler" 
```

 thnx for your feedback, I added it to the README.md

**Comment by vetash** [comment]
Hm, then in readme.md need add this:
paste your scripts to _hubot_dir_/node_modules/hubot-script-shellcmd/src/bash/handlers/
Thanks a lot!

**Comment by coderofsalvation** [comment]
done, pasted it into the readme.

Sometimes it's hard to produce a good README, so your feedback is appreciated ;)
