### ISSUE TITLE
It doesn't work on mac?

### ISSUE THREAD

**Issue by nepaul** [coderofsalvation/hubot-script-shellcmd#8]
errors!!!!!
```
hubot> hubot shellcmd
hubot> spawn!
readlink: illegal option -- f
usage: readlink [-n] [file ...]

ls: ./handlers: No such file or directory

available commands:
```

**Comment by Harwood** [comment]
I ran into this issue. If this is being run on macOS then the GNU version of readlink needs to be installed.

`brew install coreutils`

Replace instances of `readlink` with `greadlink` in `bash/handler` and all files in `bash/handlers/`.

**Comment by coderofsalvation** [comment]
Thx for the solution. Probably `brew install coreutils --default-names` will make `readlink` directly available (and link greadlink to readlink).
